FROM oven/bun:latest

WORKDIR /app

# Copy package files
COPY ./frontend/package*.json ./

# Add cache-busting argument
ARG CACHE_BUST=1
# Install dependencies with cache clearing
RUN bun install --force

# Copy frontend source code
COPY ./frontend/ .

# Expose port for development
EXPOSE 3000

# Start the development server
CMD ["bun", "run", "dev", "--", "--host", "0.0.0.0"]