FROM oven/bun:latest AS builder

WORKDIR /app

# Copy package files
COPY ./frontend/package*.json ./

# Install dependencies
RUN bun install

# Copy frontend source code
COPY ./frontend/ .

# Build the frontend
RUN bun run build


FROM nginx:alpine

# Copy the built frontend to nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy custom nginx configuration
COPY ./nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]