import { useState, useEffect } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import {
  LineChart,
  Line,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
  ReferenceLine,
  Area,
  ComposedChart,
} from "recharts";
import {
  TrendingUp,
  AlertTriangle,
  CheckCircle,
  Info,
  ArrowLeft,
  BrainCircuit,
} from "lucide-react";

// Function to generate chart data from the single backend forecast point
const generateChartData = (forecastData: any, periodDays: number) => {
  if (!forecastData) return [];

  const data = [];
  const steps = 10; // Number of points on the chart
  const predictedTotal = forecastData.predicted_value;
  const lowerTotal = forecastData.lower_bound;
  const upperTotal = forecastData.upper_bound;

  // Simple linear projection from 0 to the total predicted value
  for (let i = 0; i <= steps; i++) {
    const progress = i / steps;
    const day = Math.round(progress * periodDays);
    
    data.push({
      day: `Day ${day}`,
      forecast: predictedTotal * progress,
      upperBound: upperTotal * progress,
      lowerBound: lowerTotal * progress,
      // Add some randomness for "Actual" to simulate history vs forecast split if we had history
      actual: i < 3 ? (predictedTotal * progress) * (0.9 + Math.random() * 0.2) : null, 
    });
  }

  return data;
};

const riskMetrics = [
  { name: "Liquidity Risk", level: 35, status: "low", color: "success" },
  { name: "Volatility Risk", level: 58, status: "medium", color: "warning" },
  { name: "Burn Rate Risk", level: 42, status: "medium", color: "warning" },
  { name: "Cash Shortage Risk", level: 28, status: "low", color: "success" },
];

const scenarioData = [
  { scenario: "Best Case", projection: 68500, probability: 25 },
  { scenario: "Expected", projection: 52300, probability: 50 },
  { scenario: "Worst Case", projection: 38200, probability: 25 },
];

const ForecastResults = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const { forecastData, forecastPeriod } = location.state || {};
  const [activeView, setActiveView] = useState<"cashflow" | "scenarios">("cashflow");

  useEffect(() => {
    if (!forecastData) {
      navigate("/forecast");
    }
  }, [forecastData, navigate]);

  if (!forecastData) return null;

  const chartData = generateChartData(forecastData, Number(forecastPeriod || 30));
  const aiAnalysis = forecastData.forecast_metadata?.ai_analysis;

  const getRiskColor = (level: number) => {
    if (level < 40) return "hsl(var(--success))";
    if (level < 70) return "hsl(var(--warning))";
    return "hsl(var(--destructive))";
  };

  return (
    <div className="flex-1 space-y-4 p-4 pt-6">
      <div className="max-w-7xl mx-auto">
        <div className="flex items-center gap-4 mb-8">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => navigate("/forecast")}
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Input
          </Button>
          <div className="flex-1">
            <h2 className="text-3xl font-bold mb-2">AI Forecast Results</h2>
            <p className="text-muted-foreground">
              {forecastPeriod}-day cashflow projection generated by AI
            </p>
          </div>
          <Badge variant="outline" className="text-sm gap-1">
            <BrainCircuit className="w-3 h-3" />
            AI Powered
          </Badge>
        </div>

        {/* Key Metrics Summary */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
          <Card className="p-4">
            <div className="text-sm text-muted-foreground mb-1">
              Projected Net Flow
            </div>
            <div className="text-2xl font-bold text-foreground">
              ${forecastData.predicted_value?.toLocaleString(undefined, { maximumFractionDigits: 0 })}
            </div>
            <div className="flex items-center gap-1 mt-2 text-success text-sm">
              <TrendingUp className="w-4 h-4" />
              <span>Target</span>
            </div>
          </Card>

          <Card className="p-4">
            <div className="text-sm text-muted-foreground mb-1">
              Confidence Range
            </div>
            <div className="text-sm font-bold text-foreground mt-1">
              ${forecastData.lower_bound?.toLocaleString(undefined, { maximumFractionDigits: 0 })} - ${forecastData.upper_bound?.toLocaleString(undefined, { maximumFractionDigits: 0 })}
            </div>
            <Progress value={85} className="mt-3 h-2" />
          </Card>

          <Card className="p-4">
            <div className="text-sm text-muted-foreground mb-1">
              Risk Score
            </div>
            <div className="text-2xl font-bold text-warning">Medium</div>
            <div className="text-xs text-muted-foreground mt-2">
              Based on variance
            </div>
          </Card>

          <Card className="p-4">
            <div className="text-sm text-muted-foreground mb-1">
              Forecast Period
            </div>
            <div className="text-2xl font-bold text-foreground">{forecastPeriod} Days</div>
            <div className="text-xs text-muted-foreground mt-2">
              {forecastData.period_start} to {forecastData.period_end}
            </div>
          </Card>
        </div>

        {/* Main Chart */}
        <Card className="p-6 mb-8">
          <div className="flex items-center justify-between mb-6">
            <h3 className="text-lg font-semibold">Cashflow Trajectory</h3>
            <div className="flex gap-2">
              <Button
                variant={activeView === "cashflow" ? "default" : "outline"}
                size="sm"
                onClick={() => setActiveView("cashflow")}
              >
                Cashflow View
              </Button>
              <Button
                variant={activeView === "scenarios" ? "default" : "outline"}
                size="sm"
                onClick={() => setActiveView("scenarios")}
              >
                Scenarios
              </Button>
            </div>
          </div>

          {activeView === "cashflow" ? (
            <ResponsiveContainer width="100%" height={400}>
              <ComposedChart data={chartData}>
                <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
                <XAxis
                  dataKey="day"
                  stroke="hsl(var(--muted-foreground))"
                  tick={{ fontSize: 12 }}
                />
                <YAxis stroke="hsl(var(--muted-foreground))" tick={{ fontSize: 12 }} />
                <Tooltip
                  contentStyle={{
                    backgroundColor: "hsl(var(--card))",
                    border: "1px solid hsl(var(--border))",
                    borderRadius: "8px",
                  }}
                  formatter={(value: number) => [`$${value.toLocaleString(undefined, { maximumFractionDigits: 0 })}`, ""]}
                />
                <Legend />
                <Area
                  type="monotone"
                  dataKey="upperBound"
                  fill="hsl(var(--primary) / 0.1)"
                  stroke="none"
                  name="Optimistic"
                />
                <Area
                  type="monotone"
                  dataKey="lowerBound"
                  fill="hsl(var(--background))"
                  stroke="none"
                  name="Pessimistic"
                />
                <Line
                  type="monotone"
                  dataKey="forecast"
                  stroke="hsl(var(--success))"
                  strokeWidth={2}
                  strokeDasharray="5 5"
                  dot={false}
                  name="Projected"
                />
              </ComposedChart>
            </ResponsiveContainer>
          ) : (
            <ResponsiveContainer width="100%" height={400}>
              <BarChart data={scenarioData}>
                <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
                <XAxis dataKey="scenario" stroke="hsl(var(--muted-foreground))" />
                <YAxis stroke="hsl(var(--muted-foreground))" />
                <Tooltip
                  contentStyle={{
                    backgroundColor: "hsl(var(--card))",
                    border: "1px solid hsl(var(--border))",
                    borderRadius: "8px",
                  }}
                />
                <Bar dataKey="projection" fill="hsl(var(--primary))" radius={[8, 8, 0, 0]} />
                <Bar dataKey="probability" fill="hsl(var(--success))" radius={[8, 8, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          )}
        </Card>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Risk Analysis (Static for now) */}
          <Card className="p-6">
            <h3 className="text-lg font-semibold mb-4">Risk Analysis</h3>
            <div className="space-y-4">
              {riskMetrics.map((risk) => (
                <div key={risk.name} className="space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-medium">{risk.name}</span>
                    <Badge
                      variant={
                        risk.color === "success"
                          ? "default"
                          : risk.color === "warning"
                          ? "secondary"
                          : "destructive"
                      }
                    >
                      {risk.status}
                    </Badge>
                  </div>
                  <div className="relative h-2 bg-muted rounded-full overflow-hidden">
                    <div
                      className="absolute left-0 top-0 h-full rounded-full transition-all"
                      style={{
                        width: `${risk.level}%`,
                        backgroundColor: getRiskColor(risk.level),
                      }}
                    />
                  </div>
                  <div className="text-xs text-muted-foreground text-right">
                    {risk.level}% risk level
                  </div>
                </div>
              ))}
            </div>
          </Card>

          {/* AI Insights - DYNAMIC */}
          <Card className="p-6 border-primary/20 bg-primary/5">
            <div className="flex items-center gap-2 mb-4">
              <BrainCircuit className="w-5 h-5 text-primary" />
              <h3 className="text-lg font-semibold">AI Strategic Analysis</h3>
            </div>
            
            {aiAnalysis ? (
              <div className="prose prose-sm max-w-none">
                <div className="whitespace-pre-line text-foreground/90 leading-relaxed">
                  {aiAnalysis}
                </div>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center py-8 text-muted-foreground">
                <Info className="w-8 h-8 mb-2 opacity-50" />
                <p>No AI analysis available for this forecast.</p>
              </div>
            )}
            
            <div className="mt-4 pt-4 border-t border-primary/10 flex items-center gap-2 text-xs text-muted-foreground">
              <Info className="w-3 h-3" />
              <span>Analysis generated by Llama 4 Maverick based on your input parameters.</span>
            </div>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default ForecastResults;
