import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const Terms: React.FC = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-gray-50 py-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <Card>
          <CardHeader>
            <div className="flex lg:items-center flex-col-reverse gap-4 lg:gap-0 lg:flex-row lg:justify-between">
              <CardTitle className="text-2xl sm:text-3xl font-bold lg:text-center flex-1 capitalize">
                Terms and conditions
              </CardTitle>
              <Button
                variant="outline"
                size="sm"
                onClick={() => navigate(-1)}
                className="w-fit"
              >
                <ArrowLeft className="h-4 w-4" />
                Back
              </Button>
            </div>
          </CardHeader>
          <CardContent className="space-y-6">
            <section>
              <h2 className="text-xl font-semibold mb-3">1. Introduction</h2>
              <p className="text-gray-700 mb-3">
                Welcome to Cashflow Forecaster. These terms and conditions outline the rules and regulations for the use of our Service.
              </p>
              <p className="text-gray-700">
                By accessing this website, we assume you accept these terms and conditions. Do not continue to use Cashflow Forecaster if you do not agree to all of the terms stated on this page.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">2. License to Use</h2>
              <p className="text-gray-700 mb-3">
                Cashflow Forecaster grants you a non-exclusive, limited license to access and use our service for your personal or business financial planning purposes, subject to your compliance with these terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">3. User Accounts</h2>
              <p className="text-gray-700 mb-3">
                When you create an account with us, you must provide accurate and complete information. You are responsible for maintaining the security of your account and password. You agree to accept responsibility for all activities that occur under your account.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">4. Data and Privacy</h2>
              <p className="text-gray-700 mb-3">
                Your personal information is processed in accordance with our Privacy Policy. By using our Service, you consent to the collection and use of your data as described in our Privacy Policy.
              </p>
              <p className="text-gray-700 mb-3">
                You are responsible for the accuracy of financial data you input into the system. We are not liable for decisions made based on inaccurate data you provide.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">5. Financial Information Disclaimer</h2>
              <p className="text-gray-700 mb-3">
                The cash flow projections and financial forecasts generated by our service are estimates based on the information you provide. These projections are not guarantees of future performance and should not be used as the sole basis for making financial decisions.
              </p>
              <p className="text-gray-700">
                We are not responsible for any losses or damages that result from the use or misuse of the financial information generated by our service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">6. Prohibited Uses</h2>
              <p className="text-gray-700 mb-3">
                You agree not to use our service for any illegal activities or to violate any applicable laws or regulations. You also agree not to use our service to store or process any data that is illegal, offensive, or that could harm our reputation.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">7. Limitation of Liability</h2>
              <p className="text-gray-700 mb-3">
                In no event shall Cashflow Forecaster, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">8. Changes to Terms</h2>
              <p className="text-gray-700">
                We reserve the right to modify these terms at any time. We will notify users of any changes through the website or via email. Your continued use of the service after changes are made constitutes your acceptance of the updated terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">9. Contact Information</h2>
              <p className="text-gray-700">
                If you have any questions about these Terms, please contact us at cs@cashflow-forecaster.ryucode.com
              </p>
            </section>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default Terms;