"""Add CASCADE delete to multiple foreign keys for proper business deletion

Revision ID: 35d9f62e24a6
Revises: d39124a9ca05
Create Date: 2025-12-01 10:59:30.811814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d9f62e24a6'
down_revision = 'd39124a9ca05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'transactions', ['linked_transaction_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'forecasts', ['linked_forecast_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.alter_column('revoked',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'categories', ['parent_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'models', ['model_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'model_runs', ['model_run_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'models', ['model_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ocr_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['uploaded_by'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'forecasts', ['source_forecast_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['run_by'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'ocr_documents', ['ocr_document_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'ocr_documents', ['ocr_document_id'], ['id'])
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'])
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['run_by'], ['id'])
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'])

    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'forecasts', ['source_forecast_id'], ['id'])
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'])

    with op.batch_alter_table('ocr_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['uploaded_by'], ['id'])
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'])

    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'])

    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'models', ['model_id'], ['id'])

    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'])
        batch_op.create_foreign_key(None, 'model_runs', ['model_run_id'], ['id'])
        batch_op.create_foreign_key(None, 'models', ['model_id'], ['id'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['parent_id'], ['id'])
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'])

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.alter_column('revoked',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'transactions', ['linked_transaction_id'], ['id'])
        batch_op.create_foreign_key(None, 'forecasts', ['linked_forecast_id'], ['id'])
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'])

    # ### end Alembic commands ###
